### ISSUE TITLE
github自动化部署

### ISSUE THREAD

**Issue by luoriwusheng-xia** [luoriwusheng-xia/gsap-zh-doc#2]
操作步骤：

1. 创建一个仓库
2. vitepress 初始化一个仓库
3. 推送代码到 github
4. 在 仓库的 `settings` 里面 ，找到
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/dca96cf8-7ef5-4342-ba0f-b8a39b844a15">

5. 编写脚本
在 项目的根目录，创建下面的目录
```
.github/workflows
```
新增一个 deploy.yml  文件

编写部署脚本
```yml
name: Deploy VitePress

on:
  push:
    branches:
      - master # 仅当 main 分支有变更时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: '22.10.0' # 选择与项目兼容的 Node 版本

      - name: Install pnpm
        run: npm install -g pnpm # 全局安装 pnpm

      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      - name: Build VitePress
        run: pnpm run docs:build # 确保 package.json 中有 "docs:build" 脚本，通常为 "vitepress build docs"

      - name: list repo
        run: ls -la

      - name: List files
        run: ls -la ./dist # 增加调试命令，查看是否生成了 dist文件
      - name: pwd
        run: pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # https://github.com/marketplace/actions/github-pages-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 默认是推送到这个分支，也就是要在 github的仓库上提前创建好这个分支； 不能写master，因为会存在冲突
          # publish_branch: gh-pages
          publish_dir: ./dist
```

推送脚本到远程，会自动触发 构建，部署

**注意：**： gh-pages 分支其实是  脚本自动创建的，每一次部署，其实  runner 都会把产物  build 在这个分支。
